version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cli
    versions:
    - 3.10.0
    - 3.10.11
    - 3.10.12
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.10.6
    - 3.10.7
    - 3.10.9
    - 3.11.1
    - 3.13.1
    - 3.13.10
    - 3.13.3
    - 3.13.5
    - 3.13.6
    - 3.13.7
    - 3.13.9
    - 3.14.0
    - 3.15.1
    - 3.15.2
    - 3.16.1
    - 3.16.2
    - 3.17.1
    - 3.17.2
    - 3.18.2
    - 3.19.1
    - 3.21.10
    - 3.21.13
    - 3.21.3
    - 3.21.6
    - 3.23.0
    - 3.4.5
    - 3.4.6
    - 3.4.7
    - 3.5.0
    - 3.6.0
    - 3.7.1
    - 3.8.0
    - 3.8.1
    - 3.8.3
    - 3.8.4
    - 3.8.5
    - 3.8.6
  - dependency-name: netlify
    versions:
    - 6.1.10
    - 6.1.11
    - 6.1.13
    - 6.1.14
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.1.4
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
